version: '3.8'
services:
  redis:
    image: redis
    container_name: my-redis
    ports:
      - "6379:6379"

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api-app
    ports:
      - "3000:3000"
    depends_on:
      - redis

  worker:
    build:
      context: ./worker
      dockerfile: Dockerfile
    container_name: worker-app
    depends_on:
      - redis
    privileged: true

networks:
  sandbox-net : {}